# Config variables
XMPPSERVER = "@102mcc13.inge.itam.mx"
DEV_BUFFSIZE = 5
KNL_IPINTRQLEN = 5
KNL_MAXTIMEPROC = 5

#DEV_RECEIVED = 0
#KNL_RECEIVED = 0
#KNL_SENDED = 0

# Metrics
SND_SENDED = 0
DEV_DROPPED = 0
KNL_DROPPED = 0
APP_RECEIVED = 0

devs = list()
apps = list()
