XMPPSERVER = "@102mcc13.inge.itam.mx"
DEVBUFFSIZE = 5
APP_MAXTIMEPROC = 5
APP_TIMEBTWPROCS = 5
APP_PROBPROC = 10#50 # entre 1 y 100
apps = list()
devs = list()
# ndevs = 2
# napps = 2
SND_SENDED = 0
DEV_RECEIVED = 0
DEV_DROPPED = 0
K_RECEIVED = 0
K_SENDED = 0
